### ISSUE TITLE
Can't run latest version "Entry point for function GetThreadDescription not found"

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-Tools/radeon_memory_visualizer#1]
Hi! I can't run RadeonDeveloperPanel from latest release:

![image](https://user-images.githubusercontent.com/8597425/82127012-458f8900-97b9-11ea-8f9d-768fd3c9542f.png)

Translate from russian "Entry point for function GetThreadDescription not found"

but RadeonMemoryVisualizer.exe is working.

Windows 10 X64 (1607)

**Comment by ahosier** [comment]
Hi,

Thank you for your feedback and interest in Radeon Memory Visualizer. It appears that you're running a very old version of Windows 10 from 2016. We have seen this issue on Windows 7, which is not supported, so it may be the same issue. Please try upgrading your version of Windows 10 to the latest version or a newer version (1903 or later). Please get in touch if you're still seeing issues.
