### ISSUE TITLE
Question about requiring "custom" driver..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Tools/radeon_memory_visualizer#2]
Hi,
great product!
anyway just curious if requiring a "dedicated" driver is a temporal limitation while is being integrated into standard drivers or no plans to integrate into standard drivers?
in case is being integrated maybe even next driver ("20.5.1"?) is already expected to support it?
thanks..

**Comment by ahosier** [comment]
Hi,

Thank you for your kind words and interest in RMV. Yes, this driver is temporary at the moment. The next public driver to be released and all drivers going forward are expected to have RMV support built in.

Thanks,
Tony.
