### ISSUE TITLE
Fails to generate RMV test with test vkcube app

### ISSUE THREAD

**Issue by gggh000** [GPUOpen-Tools/radeon_memory_visualizer#3]
Using RadeonMemoryVisualizer_1.0.0.111
Once the local connection made and application is listed in RDPanel, the application remains "offline" even after the application has launched. Because of this, unable to generate trace. 
vkcube application is from C:\VulkanSDK\1.2.141.2\Bin installed by default everything. Screenshot is shared in following url:
https://u.pcloud.link/publink/show?code=XZQqoakZ7OBYL2BpfTfHaF7vzUakkjYHPx2y

**Comment by gggh000** [comment]
RX vega56, I can see it is in the supported driver list.

**Comment by gggh000** [comment]
Any update on this? More than month passed. Thanks.,

**Comment by ahosier** [comment]
Hi,

Sorry again for the delay. The RMV package was recently updated on the release page here: https://github.com/GPUOpen-Tools/radeon_memory_visualizer/releases/tag/v1.0. Download the RadeonDeveloperTools package. The Radeon Developer Panel (the RMV capture tool) has been improved. Also make sure you're running a recent Adrenaline driver and run DDU (the Display Driver Uninstaller) before installing the new driver. It sounds like something in the driver didn't get installed correctly; Vega56 should work. Let me know how you get on.

Thanks,
Tony.

**Comment by gggh000** [comment]
Hi, it works with the v1.0 release, I was able to dump and open with RMV. Thanks for improvement
