### ISSUE TITLE
Safe CRT reimplementation not very safe?

### ISSUE THREAD

**Issue by zx2c4** [GPUOpen-Tools/radeon_memory_visualizer#6]
https://github.com/GPUOpen-Tools/radeon_memory_visualizer/blob/a331b4472dafe15badfe1e0ebf4fe850779f7e41/source/parser/linux/safe_crt.cpp#L63-L75

Some of these reimplementations you might consider having a second look at.

**Comment by ahosier** [comment]
Thank you for your feedback. We are aware that these functions need further work but they are merely there for now as placeholders to get a potential Linux build working. At present, RMV for Linux isn't officially supported, though the code should build on Linux, which will allow you to load in an RMV trace captured on a windows machine.
